#!/usr/bin/env python
from __future__ import annotations
"""Regenerate the README image variants table from live tag data.

The generated block is constrained between BEGIN/END markers in README.md.
Only tags that currently exist in Docker Hub are included.
"""

import argparse
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

from latest_repo_tag import get_release_tags


HERE = Path(__file__).resolve().parent
ROOT_DIR = HERE.parent
README_FILE = ROOT_DIR / 'README.md'

MICROPYTHON_REPO = 'https://github.com/micropython/micropython.git'
DOCKERHUB_NAMESPACE = 'mattrmansfieldtx'
DOCKERHUB_REPOSITORY = 'micropython-builder'

BEGIN_MARKER = '<!-- BEGIN AUTO-GENERATED:IMAGE_VARIANTS -->'
END_MARKER = '<!-- END AUTO-GENERATED:IMAGE_VARIANTS -->'

PORT_DESCRIPTIONS = {
    'unix': 'The base image for all other ports.',
    'rp2': 'Image for RP2xxx-based boards.',
}


def dockerhub_tag_url(namespace: str, repository: str, tag: str) -> str:
    """Build a Docker Hub filtered tags URL for a specific image tag."""
    quoted = urllib.parse.quote(tag)
    return f'https://hub.docker.com/r/{namespace}/{repository}/tags?page=1&name={quoted}'


def fetch_dockerhub_tags(namespace: str, repository: str) -> set[str]:
    """Return all tag names for a Docker Hub repository via paginated API."""
    tag_names: set[str] = set()
    url = f'https://hub.docker.com/v2/namespaces/{namespace}/repositories/{repository}/tags?page_size=100'
    while url:
        req = urllib.request.Request(url, headers={'User-Agent': 'micropython-builder-readme-updater/1.0'})
        with urllib.request.urlopen(req) as response:
            payload = json.loads(response.read().decode('utf-8'))
        for item in payload.get('results', []):
            name = item.get('name')
            if name:
                tag_names.add(name)
        url = payload.get('next')
    return tag_names


def candidate_version_labels(limit: int, mpy_repo: str) -> list[str]:
    """Build ordered major.minor and major.minor.patch labels from release tags."""
    labels: list[str] = []
    seen: set[str] = set()
    for version in get_release_tags(mpy_repo, limit=limit):
        for label in (f'{version.major}.{version.minor}', version.semver):
            if label in seen:
                continue
            seen.add(label)
            labels.append(label)
    return labels


def tags_for_port(port: str, docker_tags: set[str], version_labels: list[str]) -> list[str]:
    """Return valid image tags for a port, filtered by known Docker Hub tags."""
    tags: list[str] = []
    latest = f'latest-{port}'
    if latest in docker_tags:
        tags.append(latest)
    for label in version_labels:
        tag = f'{label}-{port}'
        if tag in docker_tags:
            tags.append(tag)
    return tags


def build_table(namespace: str, repository: str, docker_tags: set[str], versions: list[str]) -> str:
    """Render the markdown image variants table using validated tag links."""
    rows = [
        '| Port      | Description                                 | Tags                                        |',
        '|-----------|---------------------------------------------|---------------------------------------------|',
    ]
    for port, description in PORT_DESCRIPTIONS.items():
        tags = tags_for_port(port, docker_tags, versions)
        tag_links = ', '.join(
            f'[{tag}]({dockerhub_tag_url(namespace, repository, tag)})'
            for tag in tags
        )
        if not tag_links:
            tag_links = 'None found on Docker Hub'
        rows.append(f'| `{port}` | {description} | {tag_links} |')
    return '\n'.join(rows)


def build_generated_block(namespace: str, repository: str, docker_tags: set[str], versions: list[str]) -> str:
    """Render the full auto-generated README block including marker comments."""
    table = build_table(namespace, repository, docker_tags, versions)
    return '\n'.join([
        BEGIN_MARKER,
        '<!-- Generated by scripts/update_readme_image_variants.py -->',
        table,
        END_MARKER,
    ])


def replace_generated_block(readme_text: str, new_block: str) -> str:
    """Replace the existing marked block in README text with new generated content."""
    pattern = re.compile(re.escape(BEGIN_MARKER) + r'.*?' + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme_text):
        raise RuntimeError('README markers not found. Add begin/end markers first.')
    return pattern.sub(new_block, readme_text)


def main() -> None:
    """CLI entry point for regenerating or checking the README image variants block."""
    p = argparse.ArgumentParser()
    p.add_argument('--readme', type=Path, default=README_FILE)
    p.add_argument('--micropython-repo', type=str, default=MICROPYTHON_REPO)
    p.add_argument('--docker-namespace', type=str, default=DOCKERHUB_NAMESPACE)
    p.add_argument('--docker-repository', type=str, default=DOCKERHUB_REPOSITORY)
    p.add_argument('--max-release-tags', type=int, default=10)
    p.add_argument('--check', action='store_true', help='Fail if README needs updates.')
    args = p.parse_args()

    versions = candidate_version_labels(args.max_release_tags, args.micropython_repo)
    docker_tags = fetch_dockerhub_tags(args.docker_namespace, args.docker_repository)
    updated_block = build_generated_block(
        namespace=args.docker_namespace,
        repository=args.docker_repository,
        docker_tags=docker_tags,
        versions=versions,
    )

    readme_text = args.readme.read_text()
    new_text = replace_generated_block(readme_text, updated_block)

    if args.check:
        if new_text != readme_text:
            raise SystemExit('README.md is out of date. Run scripts/update_readme_image_variants.py')
        print('README.md is up to date.')
        return

    args.readme.write_text(new_text)
    print(f'Updated {args.readme}')


if __name__ == '__main__':
    main()
