name: ci

on:
  push:
    branches: main

env:
  GH_REPO: ${{ github.repository }}
  DOCKERHUB_REPO: micropython-builder

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mpy-port: [rp2]
        mpy-board: [RPI_PICO, RPI_PICO_W]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      -
        name: Get image name
        shell: python
        run: |
          import os
          import sys
          port = os.environ.get('MPY_PORT')
          board = os.environ.get('MPY_BOARD')
          print(f"{port}-{board.lower()}")
        env:
          MPY_PORT: ${{ matrix.mpy-port }}
          MPY_BOARD: ${{ matrix.mpy-board }}
        id: get_image_name

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          build-args: |
            MPY_PORT=${{ matrix.mpy-port }}
            MPY_BOARD=${{ matrix.mpy-board }}
          target: rp2build
          tags: ${{ env.DOCKERHUB_REPO }}/${{ steps.get_image_name.outputs.image_name }}:test

      -
        name: Build firmware
        run: |
          mkdir -p $BUILD_DIR
          ./scripts/build_firmware.py --image $IMAGE_NAME $BUILD_DIR
        env:
          BUILD_DIR: build/${{ matrix.mpy-port }}_${{ matrix.mpy-board }}
          IMAGE_NAME: ${{ env.DOCKERHUB_REPO }}/${{ steps.get_image_name.outputs.image_name }}:test

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            MPY_PORT=${{ matrix.mpy-port }}
            MPY_BOARD=${{ matrix.mpy-board }}
          target: rp2build
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}/${{ steps.get_image_name.outputs.image_name }}:latest
